name: Assign Reviewers to Applications

on:
  schedule:
    - cron: '0 7 * * *' # run at 1 am central time (after daylight saving)
  workflow_dispatch:

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install --silent

      - name: Run Reviewer Assignment Script
        run: node scripts/assign-reviewers.js
